# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8fb498b8a3459bd2ad79c0ab0b6d0475829c657f029913e8144d46e1f92c916506d5620d2075b3581f5a217bbc783ebd79f688fe192fc398280b6d86ea6a1a

test:
  secret_key_base: 7648e2e1686c8a999d42a403477c25ec51a6ff00c1b96e3bf25d4d5592166ca3f05b02844b91cfb315dbd9fc4c2b2c29bcc1af8c5fd231cda3ca6955b28211c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
